### ISSUE TITLE
RFC: Nouveau logo

### ISSUE THREAD

**Issue by bloodyowl** [parisjs/branding#3]
## Contexte

Le logo utilisé sur les réseaux actuellement est un peu en décalage avec la charte moderne du site. 

## Proposition

Un logo qui reprenne les couleurs plus vives de la nouvelle charte, avec la Tour Eiffel pour symboliser Paris. 

### Logo

![Logo](https://user-images.githubusercontent.com/1688645/140062703-0cb4038e-1544-47dc-82ba-cd6355037df5.png)

### Favicon

![favicon@2x](https://user-images.githubusercontent.com/1688645/140062827-6d08ba82-5a71-4e3d-a5dd-0bf6b5f2f857.png)

### Card présentation de talk sur les réseaux

![Artboard Copy 2](https://user-images.githubusercontent.com/1688645/140064286-8b3f57a3-84c0-4dca-b480-59f916a0ffe4.png)

WDYT @Freddy03h @mauricesvay @jojmaht?

**Comment by Freddy03h** [comment]
Moi je suis chaud, l'ancien logo je pouvais déjà plus le voir de tout façon ^^

**Comment by jojmaht** [comment]
:shipit: 
Ça me paraît bien !
